subject_id = "0x14a0cf45bdb4ee2266b1c7496d9d3305aa60e684b2023c3fea9c10c08617482b"
issuer_id = "0x16e4953b04718a75e6b87b08bdcb3b4e7960e84604ac408c4dab76aff702a86f"
credential_type = "0x0000000000000000000000000000000000000000000000000000000000000000"
attribute_key = "0x0000000000000000000000000000000000000000000000000000000000000001"
attribute_value = "0x0000000000000000000000000000000000000000000000000000000000000019"
issued_at = "0x0000000000000000000000000000000000000000000000000000000069905d7b"
expires_at = "0x000000000000000000000000000000000000000000000000000000006b7190fb"
secret_salt = "0x05692e1402fd6856b17628d56e84a5948c3a01c672ecf6d652b0c424d463ea59"
signature = ["24", "176", "76", "145", "246", "151", "115", "148", "5", "131", "240", "78", "246", "123", "43", "195", "199", "214", "105", "177", "183", "47", "183", "125", "156", "218", "52", "133", "80", "176", "7", "203", "153", "53", "74", "182", "9", "92", "144", "204", "178", "193", "49", "13", "33", "73", "251", "206", "217", "69", "187", "163", "14", "89", "23", "186", "223", "32", "32", "144", "73", "87", "16", "97"]
pub_key_x = "0x16e4953b04718a75e6b87b08bdcb3b4e7960e84604ac408c4dab76aff702a86f"
pub_key_y = "0x29531f99cc6e18ff4bcc3062202fc9865b580ffa6e15ede4aae60ed06b38efea"
current_timestamp = "0x0000000000000000000000000000000000000000000000000000000069905d7b"
threshold = "0x0000000000000000000000000000000000000000000000000000000000000012"
dapp_context_id = "0x000000000000000000000000000000000000000000000000000000000000002a"
