[package]
name = "trivial"
type = "bin"
compiler_version = ">=0.36.0"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
shared_lib = { path = "../shared_lib" }
