subject_id = "0"
issuer_id = "0"
credential_type = "0"
attribute_key = "0"
attribute_value = "0"
issued_at = "0"
expires_at = "0"
secret_salt = "0"
signature = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
pub_key_x = "0"
pub_key_y = "0"
dapp_context_id = "0"
expected_nullifier = "0"
