[package]
name = "shared_lib"
type = "lib"
compiler_version = ">=0.36.0"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
